try to fix the upload stage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,13 +54,13 @@ jobs:
         shell: sh
         run: |
           echo ::group::Archive artifact
-          tar \
-            --dereference --hard-dereference \
-            --directory "./react/example/dist" \
-            -cvf "$RUNNER_TEMP/artifact.tar" \
-            --exclude=.git \
-            --exclude=.github \
-            .
+          tar -cvf "$RUNNER_TEMP/artifact.tar" -C "./react/example/dist" .
+          if [ -f "$RUNNER_TEMP/artifact.tar" ]; then
+            echo "Artifact tar created successfully."
+          else
+            echo "Failed to create artifact tar."
+            exit 1
+          fi
           echo ::endgroup::
 
       - name: Setup Pages
@@ -74,7 +74,7 @@ jobs:
           path: ${{ runner.temp }}/artifact.tar
           retention-days: 15
 
-  deploy-coverage:
+  deploy-page:
     runs-on: ubuntu-latest
     needs: build
 
